// <auto-generated />
using System;
using Marshall.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Marshall.Infrastructure.Migrations
{
    [DbContext(typeof(MarshallContext))]
    [Migration("20210525062417_SeedSalary")]
    partial class SeedSalary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Marshall.Domain.Entities.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Division");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Operation"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Customer care"
                        });
                });

            modelBuilder.Entity("Marshall.Domain.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "C"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "D"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ZZ"
                        });
                });

            modelBuilder.Entity("Marshall.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cargo manager"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Head manager"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cargo assistant"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sales manager"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Account executive"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marketing assistant"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Customer director"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Customer assistant"
                        });
                });

            modelBuilder.Entity("Marshall.Domain.Entities.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<double>("Comission")
                        .HasColumnType("float");

                    b.Property<double>("CompensationBonus")
                        .HasColumnType("float");

                    b.Property<double>("Contributions")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<double>("ProductionBonus")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("PositionId");

                    b.ToTable("Salary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 3215.6300000000001,
                            Contributions = 1000.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 18,
                            IdentificationNumber = "4564132",
                            Month = 10,
                            OfficeId = 2,
                            PositionId = 1,
                            ProductionBonus = 50.5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 3263.9899999999998,
                            Contributions = 1000.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 18,
                            IdentificationNumber = "4564132",
                            Month = 9,
                            OfficeId = 2,
                            PositionId = 1,
                            ProductionBonus = 50.5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 998.45000000000005,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 12,
                            IdentificationNumber = "4564132",
                            Month = 8,
                            OfficeId = 3,
                            PositionId = 2,
                            ProductionBonus = 50.5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 998.45000000000005,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 12,
                            IdentificationNumber = "4564132",
                            Month = 7,
                            OfficeId = 3,
                            PositionId = 2,
                            ProductionBonus = 50.5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 4500.0,
                            CompensationBonus = 1500.0,
                            Contributions = 1450.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 6,
                            IdentificationNumber = "4564132",
                            Month = 6,
                            OfficeId = 1,
                            PositionId = 3,
                            ProductionBonus = 2000.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 5000.0,
                            CompensationBonus = 1500.0,
                            Contributions = 1600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1,
                            EmployeeCode = "10001222",
                            EmployeeName = "Mike",
                            EmployeeSurname = "James",
                            Grade = 6,
                            IdentificationNumber = "4564132",
                            Month = 5,
                            OfficeId = 1,
                            PositionId = 3,
                            ProductionBonus = 1800.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            BaseSalary = 2995.0,
                            BeginDate = new DateTime(2020, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1980, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 3200.0,
                            Contributions = 2100.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2,
                            EmployeeCode = "10023001",
                            EmployeeName = "Kali",
                            EmployeeSurname = "Prasad",
                            Grade = 18,
                            IdentificationNumber = "14598756",
                            Month = 10,
                            OfficeId = 4,
                            PositionId = 4,
                            ProductionBonus = 3000.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 8,
                            BaseSalary = 2995.0,
                            BeginDate = new DateTime(2020, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1980, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 3200.0,
                            Contributions = 2340.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2,
                            EmployeeCode = "10023001",
                            EmployeeName = "Kali",
                            EmployeeSurname = "Prasad",
                            Grade = 18,
                            IdentificationNumber = "14598756",
                            Month = 9,
                            OfficeId = 4,
                            PositionId = 4,
                            ProductionBonus = 3200.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            BaseSalary = 3000.0,
                            BeginDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1978, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 0.0,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2,
                            EmployeeCode = "10023001",
                            EmployeeName = "Jane",
                            EmployeeSurname = "Doe",
                            Grade = 12,
                            IdentificationNumber = "1989863",
                            Month = 10,
                            OfficeId = 4,
                            PositionId = 5,
                            ProductionBonus = 4000.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1978, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 2365.7399999999998,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2,
                            EmployeeCode = "10023001",
                            EmployeeName = "Jane",
                            EmployeeSurname = "Doe",
                            Grade = 12,
                            IdentificationNumber = "1989863",
                            Month = 7,
                            OfficeId = 4,
                            PositionId = 5,
                            ProductionBonus = 3950.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 11,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1978, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 2365.7399999999998,
                            Contributions = 0.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 3,
                            EmployeeCode = "10023001",
                            EmployeeName = "Jane",
                            EmployeeSurname = "Doe",
                            Grade = 11,
                            IdentificationNumber = "1989863",
                            Month = 6,
                            OfficeId = 4,
                            PositionId = 6,
                            ProductionBonus = 2666.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1978, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 0.0,
                            CompensationBonus = 2365.7399999999998,
                            Contributions = 0.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 3,
                            EmployeeCode = "10023001",
                            EmployeeName = "Jane",
                            EmployeeSurname = "Doe",
                            Grade = 11,
                            IdentificationNumber = "1989863",
                            Month = 5,
                            OfficeId = 4,
                            PositionId = 6,
                            ProductionBonus = 2666.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 13,
                            BaseSalary = 5000.0,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 2478.96,
                            CompensationBonus = 3200.0,
                            Contributions = 1000.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 18,
                            IdentificationNumber = "8563217",
                            Month = 10,
                            OfficeId = 3,
                            PositionId = 7,
                            ProductionBonus = 0.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 14,
                            BaseSalary = 5000.0,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 2677.8800000000001,
                            CompensationBonus = 3200.0,
                            Contributions = 1000.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 18,
                            IdentificationNumber = "8563217",
                            Month = 9,
                            OfficeId = 3,
                            PositionId = 7,
                            ProductionBonus = 0.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 15,
                            BaseSalary = 3200.0,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 1845.6600000000001,
                            CompensationBonus = 998.45000000000005,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 14,
                            IdentificationNumber = "8563217",
                            Month = 8,
                            OfficeId = 3,
                            PositionId = 7,
                            ProductionBonus = 0.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 16,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 1944.22,
                            CompensationBonus = 998.45000000000005,
                            Contributions = 600.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 14,
                            IdentificationNumber = "8563217",
                            Month = 7,
                            OfficeId = 3,
                            PositionId = 7,
                            ProductionBonus = 0.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 17,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 896.22000000000003,
                            CompensationBonus = 2475.54,
                            Contributions = 0.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 6,
                            IdentificationNumber = "8563217",
                            Month = 6,
                            OfficeId = 1,
                            PositionId = 8,
                            ProductionBonus = 1899.0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 18,
                            BaseSalary = 2799.4499999999998,
                            BeginDate = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Birthday = new DateTime(1992, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comission = 801.85000000000002,
                            CompensationBonus = 2475.54,
                            Contributions = 0.0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4,
                            EmployeeCode = "10001001",
                            EmployeeName = "Ann",
                            EmployeeSurname = "Whitaker",
                            Grade = 6,
                            IdentificationNumber = "8563217",
                            Month = 5,
                            OfficeId = 1,
                            PositionId = 8,
                            ProductionBonus = 1852.21,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("Marshall.Domain.Entities.Salary", b =>
                {
                    b.HasOne("Marshall.Domain.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marshall.Domain.Entities.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marshall.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
